export const typeFilters = [
    {
        cssClass: 'grading',
        text: 'Grading System',
    },
    {
        cssClass: 'non-grading',
        text: 'Non Grading System',
    },
    {
        cssClass: 'lateral-entry',
        text: 'Lateral Entry',
    },
    {
        cssClass: 'cbcs',
        text: 'CBCS',
    },
    {
        cssClass: 'cbgs',
        text: 'CBGS',
    },
    {
        cssClass: 'as-per-coa',
        text: 'As per COA',
    },
];

export const programList = [
    {
        programLink: '/be/',
        programName: 'Bachelor of Engineering',
        programCategory: [
            {
                name: 'non-grading',
                image: 'assets/img/program/be-non-grading.png',
            },
            { name: 'grading', image: 'assets/img/program/be-grading.png' },
            { name: 'cbcs', image: 'assets/img/program/be-cbcs.png' },
            { name: 'cbgs', image: 'assets/img/program/be-cbgs.png' },
        ],
    },
    {
        programLink: '/btech/',
        programName: 'Bachelor of Technology',
        programCategory: [
            {
                name: 'non-grading',
                image: 'assets/img/program/btech-non-grading.png',
            },
            { name: 'grading', image: 'assets/img/program/btech-grading.png' },
        ],
    },
];

export const programNamesArray = [
    {
        _id: 1,
        _order: 0,
        _display: true,
        shortDisplayText: 'MBA',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 2,
        _order: 0,
        _display: true,
        shortDisplayText: 'M.Arch',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 3,
        _order: 0,
        _display: true,
        shortDisplayText: 'B.Tech',
        longDisplayText: 'Bachelor of Technology',
        parameterText: 'btech',
    },
    {
        _id: 4,
        _order: 0,
        _display: true,
        shortDisplayText: 'BE',
        longDisplayText: 'Bachelor of Engineering',
        parameterText: 'be',
    },
    {
        _id: 5,
        _order: 0,
        _display: true,
        shortDisplayText: 'BE-PTDC',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 6,
        _order: 0,
        _display: true,
        shortDisplayText: 'B.Tech-PTDC',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 7,
        _order: 0,
        _display: true,
        shortDisplayText: 'B.Pharm (PCI)',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 8,
        _order: 0,
        _display: true,
        shortDisplayText: 'B.Pharm',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 9,
        _order: 0,
        _display: true,
        shortDisplayText: 'B.Arch',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 10,
        _order: 0,
        _display: true,
        shortDisplayText: 'M.E',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 11,
        _order: 0,
        _display: true,
        shortDisplayText: 'M.Tech',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 12,
        _order: 0,
        _display: true,
        shortDisplayText: 'M.Tech (Part Time)',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 13,
        _order: 0,
        _display: true,
        shortDisplayText: 'M.Pharm',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 14,
        _order: 0,
        _display: true,
        shortDisplayText: 'M.Pharm PCI',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 15,
        _order: 0,
        _display: true,
        shortDisplayText: 'MCA 2 Year',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 16,
        _order: 0,
        _display: true,
        shortDisplayText: 'MCA',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 17,
        _order: 0,
        _display: true,
        shortDisplayText: 'MCA Dual Degree',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 18,
        _order: 0,
        _display: true,
        shortDisplayText: 'MBA Integrated',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 19,
        _order: 0,
        _display: true,
        shortDisplayText: 'DDI-PG',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 20,
        _order: 0,
        _display: true,
        shortDisplayText: 'Diploma',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 21,
        _order: 0,
        _display: true,
        shortDisplayText: 'Ph.D',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 22,
        _order: 0,
        _display: true,
        shortDisplayText: 'Ph.D Entrance',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 23,
        _order: 0,
        _display: true,
        shortDisplayText: 'PGCMB',
        longDisplayText: '',
        parameterText: '',
    },
    {
        _id: 24,
        _order: 0,
        _display: true,
        shortDisplayText: 'Pharm D',
        longDisplayText: '',
        parameterText: '',
    },
];

export const schemeNamesArray = [
    { _id: 1, shortDisplayText: 'Grading System', parameterText: 'grading' },
    {
        _id: 2,
        shortDisplayText: 'Non Grading System',
        parameterText: 'nonGrading',
    },
    {
        _id: 3,
        shortDisplayText: 'Lateral Entry',
        parameterText: 'lateralEntry',
    },
    { _id: 4, shortDisplayText: 'CBCS', parameterText: 'cbcs' },
    { _id: 5, shortDisplayText: 'CBGS', parameterText: 'cbgs' },
    { _id: 6, shortDisplayText: 'As per COA', parameterText: 'asPerCoa' },
];

export const yearArray = [
    'First Year',
    'Second Year',
    'Third Year',
    'Fourth Year',
];
export const branchArray = [
    'Computer Science',
    'Mechanical',
    'Civil',
    'Information Technology',
    'Electronics & Comm.',
];
export const semesterArray = [
    '1st semester',
    '2nd semester',
    '3rd semester',
    '4th semester',
    '5th semester',
    '6th semester',
    '7th semester',
    '8th semester',
];
