export const typeFilters = [
    {
        cssClass: 'grading',
        text: 'Grading System',
    },
    {
        cssClass: 'non-grading',
        text: 'Non Grading System',
    },
    {
        cssClass: 'lateral-entry',
        text: 'Lateral Entry',
    },
    {
        cssClass: 'cbcs',
        text: 'CBCS',
    },
    {
        cssClass: 'cbgs',
        text: 'CBGS',
    },
    {
        cssClass: 'as-per-coa',
        text: 'As per COA',
    },
];

export const programList = [
    {
        programLink: '/be/',
        programName: 'Bachelor of Engineering',
        programCategory: [
            {
                name: 'non-grading',
                image: 'assets/img/program/be-non-grading.png',
            },
            { name: 'grading', image: 'assets/img/program/be-grading.png' },
            { name: 'cbcs', image: 'assets/img/program/be-cbcs.png' },
            { name: 'cbgs', image: 'assets/img/program/be-cbgs.png' },
        ],
    },
    {
        programLink: '/btech/',
        programName: 'Bachelor of Technology',
        programCategory: [
            {
                name: 'non-grading',
                image: 'assets/img/program/btech-non-grading.png',
            },
            { name: 'grading', image: 'assets/img/program/btech-grading.png' },
        ],
    },
];

export const programNamesArray = [
    {
        _id: 1,
        _order: 1,
        _display: true,
        shortDisplayText: 'MBA',
        longDisplayText: '',
        folderName: 'mba',
    },
    {
        _id: 2,
        _order: 2,
        _display: true,
        shortDisplayText: 'M.Arch',
        longDisplayText: '',
        folderName: 'march',
    },
    {
        _id: 3,
        _order: 3,
        _display: true,
        shortDisplayText: 'B.Tech',
        longDisplayText: 'Bachelor of Technology',
        folderName: 'btech',
    },
    {
        _id: 4,
        _order: 4,
        _display: true,
        shortDisplayText: 'BE',
        longDisplayText: 'Bachelor of Engineering',
        folderName: 'be',
    },
    {
        _id: 5,
        _order: 5,
        _display: true,
        shortDisplayText: 'BE-PTDC',
        longDisplayText: '',
        folderName: 'be-ptdc',
    },
    {
        _id: 6,
        _order: 6,
        _display: true,
        shortDisplayText: 'B.Tech-PTDC',
        longDisplayText: '',
        folderName: 'btech-ptdc',
    },
    {
        _id: 7,
        _order: 7,
        _display: true,
        shortDisplayText: 'B.Pharm (PCI)',
        longDisplayText: '',
        folderName: 'bpharm-(pci)',
    },
    {
        _id: 8,
        _order: 8,
        _display: true,
        shortDisplayText: 'B.Pharm',
        longDisplayText: '',
        folderName: 'bpharm',
    },
    {
        _id: 9,
        _order: 9,
        _display: true,
        shortDisplayText: 'B.Arch',
        longDisplayText: '',
        folderName: 'barch',
    },
    {
        _id: 10,
        _order: 10,
        _display: true,
        shortDisplayText: 'M.E',
        longDisplayText: '',
        folderName: 'me',
    },
    {
        _id: 11,
        _order: 11,
        _display: true,
        shortDisplayText: 'M.Tech',
        longDisplayText: '',
        folderName: 'mtech',
    },
    {
        _id: 12,
        _order: 12,
        _display: true,
        shortDisplayText: 'M.Tech (Part Time)',
        longDisplayText: '',
        folderName: 'mtech-(part-time)',
    },
    {
        _id: 13,
        _order: 13,
        _display: true,
        shortDisplayText: 'M.Pharm',
        longDisplayText: '',
        folderName: 'mpharm',
    },
    {
        _id: 14,
        _order: 14,
        _display: true,
        shortDisplayText: 'M.Pharm PCI',
        longDisplayText: '',
        folderName: 'mpharm-pci',
    },
    {
        _id: 15,
        _order: 15,
        _display: true,
        shortDisplayText: 'MCA 2 Year',
        longDisplayText: '',
        folderName: 'mca-2-year',
    },
    {
        _id: 16,
        _order: 16,
        _display: true,
        shortDisplayText: 'MCA',
        longDisplayText: '',
        folderName: 'mca',
    },
    {
        _id: 17,
        _order: 17,
        _display: true,
        shortDisplayText: 'MCA Dual Degree',
        longDisplayText: '',
        folderName: 'mca-dual-degree',
    },
    {
        _id: 18,
        _order: 18,
        _display: true,
        shortDisplayText: 'MBA Integrated',
        longDisplayText: '',
        folderName: 'mba-integrated',
    },
    {
        _id: 19,
        _order: 19,
        _display: true,
        shortDisplayText: 'DDI-PG',
        longDisplayText: '',
        folderName: 'ddi-pg',
    },
    {
        _id: 20,
        _order: 20,
        _display: true,
        shortDisplayText: 'Diploma',
        longDisplayText: '',
        folderName: 'diploma',
    },
    {
        _id: 21,
        _order: 21,
        _display: true,
        shortDisplayText: 'Ph.D',
        longDisplayText: '',
        folderName: 'phd',
    },
    {
        _id: 22,
        _order: 22,
        _display: true,
        shortDisplayText: 'Ph.D Entrance',
        longDisplayText: '',
        folderName: 'phd-entrance',
    },
    {
        _id: 23,
        _order: 23,
        _display: true,
        shortDisplayText: 'PGCMB',
        longDisplayText: '',
        folderName: 'pgcmb',
    },
    {
        _id: 24,
        _order: 24,
        _display: true,
        shortDisplayText: 'Pharm D',
        longDisplayText: '',
        folderName: 'pharm-d',
    },
];

export const schemeNamesArray = [
    {
        _id: 1,
        _order: 1,
        _display: true,
        shortDisplayText: 'Grading System',
        longDisplayText: 'Grading System',
        folderName: 'grading',
    },
    {
        _id: 2,
        _order: 2,
        _display: true,
        shortDisplayText: 'Non Grading System',
        longDisplayText: 'Non Grading System',
        folderName: 'nonGrading',
    },
    {
        _id: 3,
        _order: 3,
        _display: true,
        shortDisplayText: 'Lateral Entry',
        longDisplayText: 'Lateral Entry',
        folderName: 'lateralEntry',
    },
    {
        _id: 4,
        _order: 4,
        _display: true,
        shortDisplayText: 'CBCS',
        longDisplayText: 'CBCS',
        folderName: 'cbcs',
    },
    {
        _id: 5,
        _order: 5,
        _display: true,
        shortDisplayText: 'CBGS',
        longDisplayText: 'CBGS',
        folderName: 'cbgs',
    },
    {
        _id: 6,
        _order: 6,
        _display: true,
        shortDisplayText: 'As per COA',
        longDisplayText: 'As per COA',
        folderName: 'asPerCoa',
    },
];

export const yearArray = [
    { _id: 1, _order: 1, _display: true, longDisplayText: 'First Year' },
    { _id: 2, _order: 2, _display: true, longDisplayText: 'Second Year' },
    { _id: 3, _order: 3, _display: true, longDisplayText: 'Third Year' },
    { _id: 4, _order: 4, _display: true, longDisplayText: 'Fourth Year' },
];

export const branchArray = [
    {
        _id: 1,
        _order: 1,
        _display: true,
        longDisplayText: 'Computer Science',
        branchShortCode: 'CS',
    },
    {
        _id: 2,
        _order: 2,
        _display: true,
        longDisplayText: 'Mechanical',
        branchShortCode: 'ME',
    },
    {
        _id: 3,
        _order: 3,
        _display: true,
        longDisplayText: 'Civil',
        branchShortCode: 'CE',
    },
    {
        _id: 4,
        _order: 4,
        _display: true,
        longDisplayText: 'Information Technology',
        branchShortCode: 'IT',
    },
    {
        _id: 5,
        _order: 5,
        _display: true,
        longDisplayText: 'Electronics & Comm.',
        branchShortCode: 'EC',
    },
];

export const semesterArray = [
    {
        _id: 1,
        _order: 1,
        _display: true,
        longDisplayText: '1st semester',
        branchShortCode: '1st sem',
    },
    {
        _id: 2,
        _order: 2,
        _display: true,
        longDisplayText: '2nd semester',
        branchShortCode: '2nd sem',
    },
    {
        _id: 3,
        _order: 3,
        _display: true,
        longDisplayText: '3rd semester',
        branchShortCode: '3rd sem',
    },
    {
        _id: 4,
        _order: 4,
        _display: true,
        longDisplayText: '4th semester',
        branchShortCode: '4th sem',
    },
    {
        _id: 5,
        _order: 5,
        _display: true,
        longDisplayText: '5th semester',
        branchShortCode: '5th sem',
    },
    {
        _id: 6,
        _order: 6,
        _display: true,
        longDisplayText: '6th semester',
        branchShortCode: '6th sem',
    },
    {
        _id: 7,
        _order: 7,
        _display: true,
        longDisplayText: '7th semester',
        branchShortCode: '7th sem',
    },
    {
        _id: 8,
        _order: 8,
        _display: true,
        longDisplayText: '8th semester',
        branchShortCode: '8th sem',
    },
];
